SmartHotelClient/Models/employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHotelClient.Models
{
    public class employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int JobTitleID { get; set; }
        public string JobTitle { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int BusinessID { get; set; }
        public string IsActive { get; set; }
    }
}

SmartHotelClient/Models/timecard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHotelClient.Models
{
    public class timecard
    {
        public int TimeCardID { get; set; }
        public int BusinessID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public Nullable<System.TimeSpan> ClockInTime { get; set; }
        public Nullable<System.TimeSpan> LunchInTime { get; set; }
        public Nullable<System.TimeSpan> LunchOutTime { get; set; }
        public Nullable<System.TimeSpan> ClockOutTime { get; set; }
        public string TotalLunchTime { get; set; }
        public string TotalWorkedHour { get; set; }
        public string Notes { get; set; }

        public virtual business business { get; set; }
        public virtual employee employee { get; set; }
    }
}

SmartHotelClient/Controllers/ClientController.cs
using SmartHotelDataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.IO;
using System.Globalization;
using System.Data;
using ClosedXML.Excel;
using System.Net.Mail;
using System.Net;
using appKeys = System.Configuration.ConfigurationManager;
using Twilio;
using Twilio.Types;
using Twilio.Rest.Api.V2010.Account;
using System.Web.Http.Cors;
using System.Security.Cryptography;
using System.Text;

namespace SmartHotelClient.Controllers
{
    [EnableCors(origins: "http://34.212.35.235:88/", headers: "*", methods: "*")]
    public class ClientController : Controller
    {
        // GET: Client


        #region DeshBoard
        [CheckSessionOut]
        public ActionResult Index()
        {
            if (!"OWNER;MANAGER;FRONTDESK;".Contains(Session["JobTitle"].ToString()))
            {
                return HttpNotFound();
            }
                return View();
        }
        [HttpPost]
        [CheckSessionOut]
        public JsonResult getPresentEmployee()
        {
            try
            {
                string[] formats = { "MM/dd/yyyy" };
                DateTime requestDate = DateTime.ParseExact(Session["reduestedDate"].ToString(), formats, new CultureInfo("en-US"), DateTimeStyles.None);
                SmartHotelRepository repObj = new SmartHotelRepository();
                var ret = Json(new
                {
                    data = repObj.getAllTiemCards(Convert.ToInt32(Session["BusinessID"]), requestDate).ToList().Select(t1 => new
                    {
                        EmployeeName = t1.employee.Name,
                        JobTitle = t1.employee.jobtitle.JobTitle1,
                        color= getJobTitleColor( t1.employee.jobtitle.JobTitle1),
                        curruntStatus = t1.ClockOutTime != null ? "ClockOut" : t1.LunchOutTime != null ? "LunchOut" : t1.LunchInTime != null ? "LunchIn" : t1.ClockInTime != null ? "ClockIn" : "Unknown",
                    }).ToArray()
                }, JsonRequestBehavior.AllowGet);
                return ret;// Json(repObj.getAllTiemCards().Select(a=>a.TimeCardID).ToArray() , JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public string getJobTitleColor(string title)
        {
            string color;

            if (title.Equals("FRONTDESK")) {
                color = "label label-info";
            }
            else if (title.Equals("HEAD HOUSEKEEPER")) {

                color = "label label-success";
            }
            else if (title.Equals("MAINTENANCE PERSON")) {
                color = "label label-warning";
            }
            else if (title.Equals("LAUNDRY PERSON")) {
                color = "label label-danger";
            }
            else if (title.Equals("HOUSEKEEPER")) {
                color = "label label-primary";
            }
            else if (title.Equals("MANAGER")) {
                color = "label label-default";
            } else {
                color = "label label-default";
            }
            return color;
        }

        [HttpPost]
        [CheckSessionOut]
        public JsonResult updateDashboardCounts()
        {
            try
            {
                string[] formats = { "MM/dd/yyyy" };
                DateTime requestDate = DateTime.ParseExact(Session["reduestedDate"].ToString(), formats, new CultureInfo("en-US"), DateTimeStyles.None);
                SmartHotelRepository repObj = new SmartHotelRepository();
                return Json(new
                {
                allAssignedRoomCount = repObj.getAllCreatedRoomLists(Convert.ToInt32(Session["BusinessID"]), requestDate).Count(),
                allCompletedRoomCount=repObj.getAllRoomListByStatus(Convert.ToInt32(Session["BusinessID"]), repObj.getRoomListStatusIdByStatus("COMPLETED"),requestDate).Count(),
                allEmployeeCount = repObj.getEmployees(Convert.ToInt32(Session["BusinessID"])).Count(),
                allAlertCount = repObj.getAllAlerts(Convert.ToInt32(Session["BusinessID"])).Count(),
                allInspectionCount = repObj.getAllInspection(Convert.ToInt32(Session["BusinessID"])).Count(),
                allInspectionCount30 = repObj.getAllInspection(Convert.ToInt32(Session["BusinessID"])).Where(b=>b.CreatedAt>=requestDate.AddDays(-30)).Count(),
                allMaintenanceCount = repObj.getAllMaintenanceRooms(Convert.ToInt32(Session["BusinessID"])).Where(b=>b.maintenancestatu.Status.Equals("OPEN")).Count(),
                    allMaintenanceCount30 = repObj.getAllMaintenanceRooms(Convert.ToInt32(Session["BusinessID"])).Where(b => b.CreatedAt >= requestDate.AddDays(-30)).Count(),
                    allLostFoundCount = repObj.getAllLostFoundRequest(Convert.ToInt32(Session["BusinessID"])).Where(b=>b.lostfoundstatu.Status.Equals("OPEN")).Count(),
                    allLostFoundCount30 = repObj.getAllLostFoundRequest(Convert.ToInt32(Session["BusinessID"])).Where(b => b.CreatedAt >= requestDate.AddDays(-30)).Count()
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ec)
            {
                return null;
            }
        }
        #endregion

        #region Common

        [HttpPost]
        [CheckSessionOut]
        public JsonResult updateAllCounts()
        {
            try
            {
                string[] formats = { "MM/dd/yyyy" };
                DateTime requestDate = DateTime.ParseExact(Session["reduestedDate"].ToString(), formats, new CultureInfo("en-US"), DateTimeStyles.None);
                SmartHotelRepository repObj = new SmartHotelRepository();
                return Json(new
                {
                    TotalClockInUser = repObj.getTotalClockedINCount(Convert.ToInt32(Session["BusinessID"]), requestDate),
                    TotalTimeOffRequests = repObj.getTotalTimeOffRequests(Convert.ToInt32(Session["BusinessID"])),
                    TotalUnreadMessage= repObj.getTotalUnreadMessageCount(Convert.ToInt32(Session["BusinessID"]), Convert.ToInt32(Session["EmployeeId"])),
                    TotalGUnreadMessage= repObj.getGuestMessageTotalUnreadCount(Convert.ToInt32(Session["BusinessID"]))
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ec)
            {
                return null;
            }
        }
        [HttpPost]
        public JsonResult SetUTC(string dateString)
        {
            Session["reduestedDateTime"] = dateString;
            Session["reduestedDate"] = dateString.Split(' ')[0].Trim();

            return Json(null);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            try
            {
                string username = collection["Username"].ToString().Trim();
                string password = collection["Password"].ToString().Trim();
                if(!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(password))
                {
                    SmartHotelRepository repObj = new SmartHotelRepository();
                    employee emp = repObj.login(username,Encryptdata(password));
                    if(emp!=null)
                    {
                        if ("OWNER;MANAGER;FRONTDESK;".Contains(emp.jobtitle.JobTitle1))
                        {
                            Session["BusinessID"] = emp.BusinessID;
                            Session["EmployeeId"] = emp.EmployeeID;
                            Session["EmployeeName"] = emp.Name;
                            Session["EmployeeSince"] = ((DateTime)emp.CreatedAt).ToString("MMM") + ". " + ((DateTime)emp.CreatedAt).ToString("yyyy");
                            Session["JobTitle"] = emp.jobtitle.JobTitle1;
                            Session["ImagePath"] = emp.ImagePath!=null?emp.ImagePath: "/Content/Alphabets/"+emp.Name.Substring(0,1).ToUpper()+".jpg";
                            Session["Username"] = emp.Username;
                            Session["Password"] =Decryptdata( emp.Password);
                            Session["Email"] = emp.Email;
                            Session["Phone"] = emp.Phone;
                            Session["BusinessName"] = emp.business.BusinessName;
                            Session["BusinessNumber"] = emp.business.BusinessNumber;
                            Session["City"] = emp.business.City;
                            string modules = "";
                            foreach (var item in (List<string>)repObj.getBusinessModuleName(emp.BusinessID))
                            {
                                modules += item + ";";
                            }
                            Session["SubscribedModules"] = modules;
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Message = "You are not eligible to view client module";
                            ViewBag.Username = username;
                            return View();
                        }
                    }
                    else
                    {
                        if(repObj.getEmployeeIdFromUserName(username)>0)
                        {
                            ViewBag.Message = "Enter Correct Password";
                            ViewBag.Username = username;
                            return View();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                
            }
            @ViewBag.Message = "Enter Correct Username and Password";
            return View();
        }

        [HttpPost]
        public ActionResult LoginSuperAdmin(FormCollection collection)
        {

SmartHotelClient/Views/Client/ErrorPage.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("IncludeLink")
  
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("Header")

        @Html.Partial("SideMenu")

        <!-- Content Wrapper. Contains page content -->

        <div class="content-wrapper">
            <br />
            <br />
            <center>
                <h2>@ViewData["Message"]</h2>
            </center>
        </div>

        <!-- /.content-wrapper -->
        @Html.Partial("Footer")

        @Html.Partial("RightSideBar")

    </div>

</body>
</html>

SmartHotelClient/Views/Client/Header.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="/Client/index" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
            <b>S</b>H
        </span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
            <b>BSmart</b>Hotel
        </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <div class="col-lg-3">

            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        </div>
        <div class="col-lg-6">
            <center>
                <h4>
                    <p class="align-middle" style="color:#ffffff">
                        <b>@Session["BusinessName"]</b> ,
                        @Session["City"]
                    </p>
                </h4>
            </center>
            
        </div>
        <div class="col-lg-3">

            <div class="navbar-custom-menu">

                <ul class="nav navbar-nav">

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @{
                                if (Session["ImagePath"] == null || Session["ImagePath"] == "")
                                {
                                    <img data-name="@Session["EmployeeName"]" class="profile1 user-image" />
                                }
                                else
                                {
                                    <img src="@Session["ImagePath"]" class="user-image" alt="User Image">
                                }
                            }

                            <span class="hidden-xs">@Session["EmployeeName"]</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                @{
                                    if (Session["ImagePath"] == null || Session["ImagePath"] == "")
                                    {
                                        <img data-name="@Session["EmployeeName"]" class="profile2 img-circle" />
                                    }
                                    else
                                    {
                                        <img src="@Session["ImagePath"]" class="img-circle" alt="User Image">
                                    }
                                }


                                <p>
                                    @Session["EmployeeName"] - @Session["JobTitle"]
                                    <small>Employed since @Session["EmployeeSince"]</small>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">

                                    <button type="button" data-toggle="modal" class="btn btn-default btn-flat" data-target="#editProfileModel" value=@Session["EmployeeId"]>Profile</button>

                                    <button type="button" data-toggle="modal" class="btn btn-default btn-flat" data-target="#editPasswordModel" value=@Session["EmployeeId"]>Edit Password</button>
                                </div>
                                <div class="pull-right">
                                    <a href="~/Client/Logout" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="modal modal-warning fade" id="editPasswordModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <form  name="editPasswordForm" id="editPasswordForm" method="post" >
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Change Password</h4>
                </div>
                <div class="modal-body">
                    
                    <label for="exampleInputEmail1">Old Password</label>
                    <input type="password" class="form-control" id="editProfileoldPassword" name="editProfileoldPassword" placeholder="Enter Old Password" required onkeyup="editOldPasswordCheck()">
                    <p id="editProfileStatus"><input type="hidden" id="editProfileusernameValidator" name="editProfileusernameValidator" value="false" /></p>
                    <label for="exampleInputEmail1">Password</label>
                    <input type="password" class="form-control" id="editProfilePassword" name="editProfilePassword" placeholder="Enter Password"  onkeyup="editProfilecheck();" required>
                    <label for="exampleInputEmail1">Confirm Password</label>
                    <input type="password" class="form-control" id="editProfileCnfPassword" name="editProfileCnfPassword" placeholder="Confirm Password" onkeyup="editProfilecheck();" required><span id='editProfilemessage'></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" id="closePassword">Close</button>
                    <button type="button" class="btn btn-outline" onclick="editPassword()">Save changes</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="modal modal-warning fade" id="editProfileModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="/Client/EditEmployee" name="editProfile" id="editProfile" method="post" onsubmit="return editProfilevalidateForm()">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Profile</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="editProfileID" name="editProfileID" />
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" id="editProfileName" name="editProfileName" placeholder="Enter Employee Name " value="@Session["EmployeeName"]" required>

                    <label for="exampleInputEmail1">Phone</label>
                    <input type="tel" class="form-control" id="editProfilePhone" name="editProfilePhone" placeholder="Enter Employee Phone number" value="@Session["Phone"]" required>
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" class="form-control" id="editProfileEmail" name="editProfileEmail" placeholder="Enter Employee Email address" value="@Session["Email"]">

                    @*<label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="editProfileUsername" name="editProfileUsername" placeholder="Enter Username" value="@Session["Username"]" required onchange="editProfileUserCheck()">
                    <p id="editProfileStatus"><input type="hidden" id="editProfileusernameValidator" name="editProfileusernameValidator" value="true" /></p>
                    <label for="exampleInputEmail1">Password</label>
                    <input type="password" class="form-control" id="editProfilePassword" name="editProfilePassword" placeholder="Enter Password" value="@Session["Password"]" onkeyup="editProfilecheck();" required>
                    <label for="exampleInputEmail1">Confirm Password</label>
                    <input type="password" class="form-control" id="editProfileCnfPassword" name="editProfileCnfPassword" placeholder="Confirm Password" value="@Session["Password"]" onkeyup="editProfilecheck();" required><span id='editProfilemessage'></span>*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" id="closeProfile">Close</button>
                    <button type="button" class="btn btn-outline" onclick="editProfilevalidateForm()">Save changes</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script>
    $(document).ready(function () {
        $('.profile1').initial({height:25,width:25,fontSize:18}); 
        $('.profile2').initial({height:83,width:83,fontSize:70}); 
    });
</script>
<script>
    var editProfilecheck = function () {
            if (document.getElementById('editProfilePassword').value ==
              document.getElementById('editProfileCnfPassword').value) {
                document.getElementById('editProfilemessage').style.color = 'green';
                document.getElementById('editProfilemessage').innerHTML = 'matching';
            } else {
                document.getElementById('editProfilemessage').style.color = 'red';
                document.getElementById('editProfilemessage').innerHTML = 'not matching';
            }
        }
</script>
<script>
    function editProfilevalidateForm() {
        if($("#editProfile")[0].checkValidity())
        {
            $.post("@Url.Action("editProfile", "Client")",
        {
            id: @Session["EmployeeId"],
            name: $("#editProfileName").val(),
            phone: $("#editProfilePhone").val(),
            email: $("#editProfileEmail").val(),
            username:"",// $("#editProfileUsername").val(),
            password: ""//$("#editProfilePassword").val()
        },
        function (data) {
            if (data == 1) {
                //alert("Profile edited Successfully");
                $("#closeProfile").click();

            }
            else{
                //alert("Something went wrong please try again ! ");

            }
        });
        }
        else
        {
            $("#editProfile")[0].reportValidity();
        }
        }
</script>
<script>
    function editPassword() {
        if($("#editPasswordForm")[0].checkValidity())
        {
            if ((document.getElementById('editProfilePassword').value == document.getElementById('editProfileCnfPassword').value) && "@Session["Password"]" == $("#editProfileoldPassword").val()) {
                $.post("@Url.Action("editProfile", "Client")",
            {
                id: @Session["EmployeeId"],
                name: "",
                phone: "",
                email: "",
                username: $("#editProfileUsername").val(),
                password: $("#editProfilePassword").val()
            },
            function (data) {
                if (data == 1) {
                    //alert("Psssword changed Successfully");
                    $("#editPasswordForm")[0].reset();
                    $("#editProfileStatus").html('<input type="hidden" id="editProfileusernameValidator" name="editProfileusernameValidator" value="false"/>');
                    $("#editProfilemessage").html("");
                    $("#closePassword").click();

                }
                else{
                    //alert("Something went wrong please try again ! ");

                }
            });
            }
        }
        else
        {
            $("#editPasswordForm")[0].reportValidity();
        }
        }
</script>
<script>

    function editOldPasswordCheck() {
        @*$("#editProfileStatus").html("Checking...");
            $.post("@Url.Action("checkOldPassword", "Client")",
        {
            oldpassword: $("#editProfileoldPassword").val(),
            id: @Session["EmployeeId"]
        },
        function (data) {*@
        if ("@Session["Password"]" == $("#editProfileoldPassword").val()) {
                $("#editProfileStatus").html('<font color="Green">Match Old Password.</font><input type="hidden" id="editProfileusernameValidator" name="editProfileusernameValidator" value="true"/>');
                $("#editProfileUsername").css("border-color", "Green");

            }
            else {
                $("#editProfileStatus").html('<font color="Red">Wrong Old Password </font><input type="hidden" id="editProfileusernameValidator" name="editProfileusernameValidator" value="false"/>');
                $("#editProfileUsername").css("border-color", "Red");

            }
        //});
        }
</script>
@if (Session["reduestedDate"] == null || string.IsNullOrEmpty(Session["reduestedDate"].ToString()))
{

    <script type="text/javascript">

        var d = new Date();
        var date = d.getDate();
        var month = (d.getMonth() + 1);
        if (month<10)
        {
            month = "0" + (d.getMonth() + 1);
        }
        if (date < 10) {
            date = "0" + d.getDate();
        }
        var datetext = d.toTimeString();
        datetext = datetext.split(' ')[0];
        var dateString = month + "/" + date + "/" + d.getFullYear() + " " + datetext;
            $.post('/Client/SetUTC', { dateString }, function (data) { location.reload(); });
    </script>
}
<!-- Left side column. contains the logo and sidebar -->

SmartHotelClient/Views/Client/Help.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("IncludeLink")

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    @Html.Partial("Header")
    @Html.Partial("SideMenu")

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Need Help?
       <!--  <small>Control panel</small> -->
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Help</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="color: black">
           
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <section class="content-header">
                  <form name="scheduleMForm" id="scheduleMForm">
                      <h1>
                          Would you like to Schedule a meeting?
                      </h1>
                      <div>
                          <div class="form-group">
                              <label>Enter Date and time:</label>
                              <div><input type="text" value="" name="datetime" id="datetime" required /></div>
                              <label>Comment:</label>
                              <div><input type="text" value="" name="commentS" id="commentS" required /></div>
                              <!-- /.input group -->
                          </div>
                      </div>

                      <div style="margin-bottom: 20px"><button type="button" onclick="sendScheduleMail()" class="btn btn-success" data-toggle="modal" data-target="#modal-danger">Schedule Meeting</button></div>
                  </form>
                      </section>
          
              </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="color: black">
           
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <section class="content-header">
                <h1>
                 Have a Question? Would you like to ask?
                </h1>
                <h4 style="margin-top: 25px"><b>
                 <p>Email for support : support@BSmarthotel.com</p>
                 <p> Email for Info : info@BSmarthotel.com</p>
                 <p> Email for Sales : sales@BSmarthotel.com</p>
                </b></h4>
              </section>
          
              </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box" style="color: black">
           
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <section class="content-header">
                <h1>
                Would you like to talk to someone right now?
                </h1>
                <h4 style="margin-top: 25px">
                <b> <p>Call  : +1(323) 374-5055</p>
                  <p>Text : +1(323) 643-9608</p>
                </b></h4>
              </section>
          
              </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
    </div>
     </div>
    </section>
      
     

  
  </div>
  <!-- /.content-wrapper -->
  @Html.Partial("Footer")
    

  <!-- Control Sidebar -->
    @Html.Partial("RightSideBar")
</div>
<!-- ./wrapper -->


<!-- page script -->
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
    <script>
        function sendScheduleMail() {
            if ($("#scheduleMForm")[0].checkValidity())
                {
        $.post("@Url.Action("sendHelpMail", "Client")",
    {
        datet: $("#datetime").val(),
        comment: $("#commentS").val()
    },
    function (data) {
        if (data == 1) {
            //$("#editcancel").click();
            //alert("Alerts edited Successfully");
            $("#scheduleMForm")[0].reset();
        }
        else{
            //alert("Something went wrong please try again ! ");

        }
    });
        }
        else
        {
                $("#scheduleMForm")[0].reportValidity();
        }
        }
    </script>
</body>
</html>